language: cpp
compiler: gcc

# There are two options:
#
# Option 1:
#
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-5
#
# Option 2:
#
#  install:
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq g++-5
# 
# Speed measurements, all done one master branch:
#
# Option | Commit  | Build time (sec) 
#      1 | 
#      1 | cc47e2a | 89
#      1 | 2a22f81 | 78
#      1 | 8f424b1 | 73 
#      2 | 4ed74ee | 106
#      2 | 06578ff | 135 


# Is this faster?
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  # C++14
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  #- sudo apt-get update -qq

install: 
  # C++14
  #- sudo apt-get install -qq g++-5
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14
